SET IDENTITY_INSERT CAMISA ON;
INSERT INTO CAMISA (ID_CAMISA, NOME_CAMISA, TIPO_CAMISA, TAMANHO, PREÇO, COR) VALUES
('001', 'camisa oversised', 'gola u', 'pp', 'R$150', 'preta'), 
('002', 'camisa oversised', 'gola u', 'p', 'R$150', 'preta'),
('003', 'camisa oversised', 'gola u', 'm', 'R$150', 'preta'),
('004', 'camisa oversised', 'gola u', 'g', 'R$150', 'preta'), 
('005', 'camisa oversised', 'gola u', 'gg', 'R$150', 'preta'), 
('006', 'camisa oversised', 'gola u', 'pp', 'R$150', 'branca'),
('007', 'camisa oversised', 'gola u', 'p', 'R$150', 'branca'),
('008', 'camisa oversised', 'gola u', 'm', 'R$150', 'branca'), 
('009', 'camisa oversised', 'gola u', 'g', 'R$150', 'branca'), 
('010', 'camisa oversised', 'gola u', 'gg', 'R$150', 'branca'),
('011', 'camisa oversised', 'gola u', 'pp', 'R$150', 'azul'), 
('012', 'camisa oversised', 'gola u', 'p', 'R$150', 'azul'), 
('013', 'camisa oversised', 'gola u', 'm', 'R$150', 'azul'),
('014', 'camisa oversised', 'gola u', 'g', 'R$150', 'azul'),
('015', 'camisa oversised', 'gola u', 'gg', 'R$150', 'azul'), 
('016', 'camisa oversised', 'gola u', 'pp', 'R$150', 'verde'),
('017', 'camisa oversised', 'gola u', 'p', 'R$150', 'verde'), 
('018', 'camisa oversised', 'gola u', 'm', 'R$150', 'verde'),
('019', 'camisa oversised', 'gola u', 'g', 'R$150', 'verde'),
('020', 'camisa oversised', 'gola u', 'gg', 'R$150', 'verde'), 
('021', 'camisa oversised', 'gola u', 'pp', 'R$150', 'cinza'), 
('022', 'camisa oversised', 'gola u', 'p', 'R$150', 'cinza'), 
('023', 'camisa oversised', 'gola u', 'm', 'R$150', 'cinza'), 
('024', 'camisa oversised', 'gola u', 'g', 'R$150', 'cinza'), 
('025', 'camisa oversised', 'gola u', 'gg', 'R$150', 'cinza');