SET IDENTITY_INSERT CAMISA OFF;
INSERT INTO CAMISA (NOME_CAMISA, TIPO_CAMISA, TAMANHO, PREÇO, COR) VALUES
('camisa manga longa', 'gola u', 'pp', 'R$200', 'preta'), 
('camisa manga longa', 'gola u', 'p', 'R$200', 'preta'), 
('camisa manga longa', 'gola u', 'm', 'R$200', 'preta'), 
('camisa manga longa', 'gola u', 'g', 'R$200', 'preta'), 
('camisa manga longa', 'gola u', 'gg', 'R$200', 'preta'),
('camisa manga longa', 'gola u', 'pp', 'R$200', 'branca'), 
('camisa manga longa', 'gola u', 'p', 'R$200', 'branca'), 
('camisa manga longa', 'gola u', 'm', 'R$200', 'branca'), 
('camisa manga longa', 'gola u', 'g', 'R$200', 'branca'), 
('camisa manga longa', 'gola u', 'gg', 'R$200', 'branca'), 
('camisa manga longa', 'gola u', 'pp', 'R$200', 'azul'), 
('camisa manga longa', 'gola u', 'p', 'R$200', 'azul'), 
('camisa manga longa', 'gola u', 'm', 'R$200', 'azul'), 
('camisa manga longa', 'gola u', 'g', 'R$200', 'azul'), 
('camisa manga longa', 'gola u', 'gg', 'R$200', 'azul'), 
('camisa manga longa', 'gola u', 'pp', 'R$200', 'verde'), 
('camisa manga longa', 'gola u', 'p', 'R$200', 'verde'), 
('camisa manga longa', 'gola u', 'm', 'R$200', 'verde'), 
('camisa manga longa', 'gola u', 'g', 'R$200', 'verde'), 
('camisa manga longa', 'gola u', 'gg', 'R$200', 'verde'), 
('camisa manga longa', 'gola u', 'pp', 'R$200', 'cinza'), 
('camisa manga longa', 'gola u', 'p', 'R$200', 'cinza'),
('camisa manga longa', 'gola u', 'm', 'R$200', 'cinza'),
('camisa manga longa', 'gola u', 'g', 'R$200', 'cinza'), 
('camisa manga longa', 'gola', 'gg', 'R$200', 'cinza');
