create database loja
GO

USE loja
GO

CREATE TABLE CLIENTES (
   ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
   NOME_CLIENTE VARCHAR(30),
   RUA VARCHAR(30),
   CIDADE VARCHAR(30),
   ESTADO VARCHAR(30),
   CEP VARCHAR(30)
   );

CREATE TABLE CAMISA (
   ID_CAMISA INT PRIMARY KEY IDENTITY(1,1),
   NOME_CAMISA VARCHAR(30),
   TIPO_CAMISA VARCHAR(30),
   TAMANHO VARCHAR(2),
   PREÇO VARCHAR(10),
   COR VARCHAR(10)
);