CREATE DATABASE SolucaoCinema;
GO
USE SolucaoCinema;
GO
 
CREATE TABLE Usuario (
   idUsuario INT    IDENTITY (1, 1) NOT NULL,
   Usuario VARCHAR (10) NOT NULL,
   Senha VARCHAR (10),

   PRIMARY KEY CLUSTERED (idUsuario ASC)
);
GO

CREATE TABLE Cinema (
	idCinema INT IDENTITY (1, 1) NOT NULL,
	nmCinema VARCHAR (20) NOT NULL,
	dsEndereço VARCHAR (150) NOT NULL,
	mrSales INT NOT NULL,
	PRIMARY KEY CLUSTERED (idCinema ASC)
);
GO

CREATE TABLE Genero {
idGenero INT IDENTITY (1, 1) NOT NULL,
idGenero VARCHAR (20) NOT NULL,

PRIMARY KEY CLUSTERED (idGenero ASC)
};
GO